# Generated by Django 3.0.8 on 2020-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolist',
            name='image',
            field=models.ImageField(upload_to='youtube/VideoList'),
        ),
    ]
